
["General settings"]
	#If set to true player joining the world for the first time will be given the Wizard Elementary - a questline guidebook throughout the mod's mechanics (if not given at start it still can be crafted by the player). (default: true)
	"Give Wizard Elementary at start" = true
	#If set to true players will be displayed a custom toast congratulating them on completing a quest. (default: true)
	"Announce Wizard Elementary's quest completion" = true

["Disabling mobs"]
	#The mobs may spawn inside Even More Magic structures when a player approaches the structure for the first time. You can disable some of them. (true = disabled)
	"Eternal Ghost" = false
	"Explosive Ghost" = false
	Fate = false
	"Fire Spider" = false
	"Poisoned Pumpkin" = false
	Rotater = false
	Shaker = false
	Spike = false
	Spooner = false
	Tornado = false

["Disabling scrolls"]
	#The disabled scrolls will not be obtainable in survival (wands crafted from them will not be craftable as a consecuence - it will be noted in their description).  (true = disabled)
	"Scroll Of Avalanche" = false
	"Scroll Of Blooming" = false
	"Scroll Of Cloud" = false
	"Scroll Of DNA Detector" = false
	"Scroll Of Dragon Breath" = false
	"Scroll Of Drizzle" = false
	"Scroll Of Ellusion" = false
	"Scroll Of Fireballs" = false
	"Scroll Of Giant Roots" = false
	"Scroll Of Grass Stomp" = false
	"Scroll Of Growth" = false
	"Scroll Of Healthy Blood" = false
	"Scroll Of Ice Spikes" = false
	"Scroll Of Incineration" = false
	"Scroll Of Landslide" = false
	"Scroll Of Lavadrop" = false
	"Scroll Of Leaflet" = false
	"Scroll Of Lightning" = false
	"Scroll Of Magma Blades" = false
	"Scroll Of Magnetism" = false
	"Scroll Of Obsidian" = false
	"Scroll Of Shiny Treasure" = false
	"Scroll Of Stone Spikes" = false
	"Scroll Of Wind Blast" = false
	"Scroll Of Wind Repeller" = false

["Disabling wands"]
	#The disabled wands will not be craftable (their upgraded versions as well). The special wands (which basic versions are crafted at vanilla Crafting Table) will be decomposed back to their ingredients with a message that the wand is disabled as soon as they get crafted.  (true = disabled)
	"Blazing Wand" = false
	"Boulder Wand" = false
	"Bouncy Stone Wand" = false
	"Bucket Wand" = false
	"Cursor Wand" = false
	"Dashereeng Wand" = false
	"Dirt Wand" = false
	"Generous Wand" = false
	"Glowing Wand" = false
	"Igniter Wand" = false
	"Incinerating Wand" = false
	"Jetpack Wand" = false
	"Kelp Wand" = false
	"Lava Diving Wand" = false
	"Leaves Chomping Wand" = false
	"Log Wand" = false
	"Nature Wand" = false
	"Repelling Wand" = false
	"Rubble Wand" = false
	"Rumble Wand" = false
	"Shell Wand" = false
	"Sonar Wand" = false
	"Torch Wand" = false
	"Wand Of Ancient Flowers" = false
	"Wand Of Bioluminecance" = false
	"Wand Of Blooming" = false
	"Wand Of Cave Escape" = false
	"Wand Of Chaotic Wind" = false
	"Wand Of Cloudy Gem" = false
	"Wand Of Cobbled Stone" = false
	"Wand Of Conductive Gem" = false
	"Wand Of DNA Scanning" = false
	"Wand Of Downpour" = false
	"Wand Of Dragon Hiccup" = false
	"Wand Of Dragon Jaw" = false
	"Wand Of Dragonborn" = false
	"Wand Of Evasion" = false
	"Wand Of Fireball" = false
	"Wand Of Flying Leaves" = false
	"Wand Of Forest Wrath" = false
	"Wand Of Glass Of Fire" = false
	"Wand Of Grass Blast" = false
	"Wand Of Grass Growth" = false
	"Wand Of Grass Steed" = false
	"Wand Of Grass Step" = false
	"Wand Of Groundslide" = false
	"Wand Of Healthy Aura" = false
	"Wand Of Healthy Blood" = false
	"Wand Of Huge Growth" = false
	"Wand Of Ice Rain" = false
	"Wand Of Ice Spikes" = false
	"Wand Of Iron Ore" = false
	"Wand Of Landslide" = false
	"Wand Of Lava Glass" = false
	"Wand Of Lavarain" = false
	"Wand Of Lavashield" = false
	"Wand Of Lavastick" = false
	"Wand Of Light Detection" = false
	"Wand Of Lightning Focus" = false
	"Wand Of Magma Blade" = false
	"Wand Of Magma Blades" = false
	"Wand Of Magma Whirl" = false
	"Wand Of Magnet" = false
	"Wand Of More Crops" = false
	"Wand Of Myst" = false
	"Wand Of Obsidian Chainsaw" = false
	"Wand Of Obsidian Gem" = false
	"Wand Of Persistance" = false
	"Wand Of Railgun" = false
	"Wand Of Rainy Cloud" = false
	"Wand Of River Serpent" = false
	"Wand Of Root" = false
	"Wand Of Sharp Leaves" = false
	"Wand Of Sharp Petals" = false
	"Wand Of Spring Tree" = false
	"Wand Of Stone Slide" = false
	"Wand Of Stone Spike" = false
	"Wand Of Sunrise Fairy" = false
	"Wand Of Tesla Coil" = false
	"Wand Of Tiny Rain" = false
	"Wand Of Treasure Fairy" = false
	"Wand Of Unpredictable Fireballs" = false
	"Wand Of Vision" = false
	"Wand Of Vivern" = false
	"Wand Of Weakness Analyser" = false
	"Wand Of Windpull" = false
	"Wand Of Windpush" = false
	"Wand Of Windrush" = false
	"Wand Of Windslide" = false
	"Wand Of Winter" = false

